#docker-compose 版本号
version: '3.6'
# https://github.com/docker/docker.github.io/blob/master/compose/compose-file/compose-file-v2.md
services:
  consul:
    command: agent -server -bootstrap -rejoin -client=0.0.0.0 -ui -log-level=warn
    #基于现有的镜像(latest为最新版本)
    image: consul:latest
    #DNS: The DNS server (TCP and UDP)	8600
    #HTTP: The HTTP API (TCP Only)	8500
    #server: Server RPC address (TCP Only)	8300
    #https://www.consul.io/docs/install/ports.html
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8500:8500"
      - "8600:8600"
  jaeger:
    image: jaegertracing/all-in-one:latest
    links:
      - consul
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
  gateway:
    build: gateway/gin
    command: --registry_address=consul:8500 --server_port=8080
    links:
      - consul
#    depends_on:
    ports:
      - "8080:8080"
    environment:
      - JAEGER_SERVICE_NAME=gateway
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
  api_buy:
    build: api/buy
    command: --registry_address=consul:8500
    links:
      - consul
    environment:
      - JAEGER_SERVICE_NAME=api_buy
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
#    depends_on:
#    deploy:
#      mode: replicated
#      replicas: 3
  srv_goods:
    build: srv/goods
    command: --registry_address=consul:8500
    links:
      - consul
#    depends_on:
#    deploy:
#      mode: replicated
#      replicas: 3
  src_order:
    build: srv/order
    command: --registry_address=consul:8500
    links:
      - consul
#    depends_on:
#    deploy:
#      mode: replicated
#      replicas: 3
